# Generated by Django 3.2.3 on 2021-05-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0002_auto_20210521_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200, unique=True), max_length=200, unique=True),
        ),
    ]
