# Generated by Django 3.2.3 on 2021-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
