# Generated by Django 3.2.3 on 2021-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0007_auto_20210521_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='opensource/static/img/default-img.jpg', upload_to='opensource/static/img'),
        ),
    ]
