# Generated by Django 3.2.3 on 2021-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='iti/opensource/static/img/default-img.jpg', upload_to='iti/opensource/static/img'),
        ),
    ]
