# Generated by Django 3.2.3 on 2021-05-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0014_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
