# Generated by Django 3.2.3 on 2021-05-22 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opensource', '0015_badword'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badword',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
