# Generated by Django 3.2.3 on 2021-05-22 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opensource', '0018_auto_20210522_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='opensource.Subscribtion', to=settings.AUTH_USER_MODEL),
        ),
    ]
