# Generated by Django 3.2.3 on 2021-05-22 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opensource', '0019_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opensource.category'),
        ),
        migrations.AlterField(
            model_name='subscribtion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
