# Generated by Django 3.2.3 on 2021-05-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0020_auto_20210522_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
