# Generated by Django 3.2.3 on 2021-05-22 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opensource', '0021_alter_subscribtion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribtion',
            unique_together={('user', 'category')},
        ),
    ]
