# Generated by Django 3.2.3 on 2021-05-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0016_auto_20210522_0424'),
        ('opensource', '0022_auto_20210522_1637'),
    ]

    operations = [
    ]
