# Generated by Django 3.0 on 2021-05-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0025_auto_20210525_1859'),
        ('opensource', '0026_alter_comment_options'),
    ]

    operations = [
    ]
