# Generated by Django 3.0 on 2021-05-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0025_post_tags'),
        ('opensource', '0027_merge_20210525_1953'),
    ]

    operations = [
    ]
