# Generated by Django 3.0 on 2021-06-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0028_merge_20210525_2241'),
        ('opensource', '0024_auto_20210522_2259'),
    ]

    operations = [
    ]
