# Generated by Django 3.0 on 2021-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource', '0023_merge_0016_auto_20210522_0424_0022_auto_20210522_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscribtion',
            name='subscribed_on',
            field=models.DateField(auto_now=True),
        ),
    ]
